AutomatedTellerMachine/Controllers/CheckingAccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutomatedTellerMachine.Models;
using Microsoft.AspNet.Identity;

namespace AutomatedTellerMachine.Controllers
{
    [Authorize]
    public class CheckingAccountController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: CheckingAccount
        public ActionResult Index()
        {
            return View();
        }

        // GET: CheckingAccount/Details
        public ActionResult Details()
        {
            var userId = User.Identity.GetUserId();
            var checkingAccount = db.CheckingAccounts.Where(c => c.ApplicationUserId == userId).First();
            return View(checkingAccount);
        }

        [Authorize(Roles = "Admin")]
        public ActionResult DetailsForAdmin(int id)
        {
            var checkingAccount = db.CheckingAccounts.Find(id);
            return View("Details", checkingAccount);
        }

        // GET: CheckingAccount/List
        [Authorize(Roles = "Admin")]
        public ActionResult List()
        {
            return View(db.CheckingAccounts.ToList());
        }

        // GET: CheckingAccount/Statement
        public ActionResult Statement(int id)
        {
            var checkingAccount = db.CheckingAccounts.Find(id);
            return View(checkingAccount.Transactions.ToList());
        }

        // GET: CheckingAccount/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CheckingAccount/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: CheckingAccount/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: CheckingAccount/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: CheckingAccount/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: CheckingAccount/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

AutomatedTellerMachine/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutomatedTellerMachine.Filters;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using AutomatedTellerMachine.Models;

namespace AutomatedTellerMachine.Controllers
{
    public class HomeController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: /home/index/
        [Authorize]
        public ActionResult Index()
        {
            // Get checking account Id associated with logged-in user
            var userId = User.Identity.GetUserId();
            var checkingAccountId = db.CheckingAccounts.Where(c => c.ApplicationUserId == userId).First().Id;
            ViewBag.CheckingAccountId = checkingAccountId;

            // Get Pin associated with logged-in user
            var manager = HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            var user = manager.FindById(userId);
            ViewBag.Pin = user.Pin;

            return View();
        }

        // GET: /home/about/
        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View("About");
        }

        // GET: /home/contact/
        [HttpGet]
        public ActionResult Contact()
        {
            ViewBag.TheMessage = "Having trouble? Send us a message.";

            return View();
        }

        [HttpPost]
        public ActionResult Contact(string message)
        {
            // TODO: send message to HQ
            ViewBag.TheMessage = "Thanks, we got your message!";
            return PartialView("_ContactThanks");
        }

        public ActionResult Foo()
        {
            return View("About");
        }

        [Route("serial")]
        public ActionResult Serial(string letterCase)
        {
            var serial = "ASPNETMVC5ATM1";
            if (letterCase == "lower")
            {
                return Content(serial.ToLower());
            }
            return Content(serial);
            //return new HttpStatusCodeResult(403);
            //return Json(new { name = "serial", value = serial }, JsonRequestBehavior.AllowGet);
            //return RedirectToAction("Index");
        }
    }
}

AutomatedTellerMachine/Controllers/TransactionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutomatedTellerMachine.Models;
using AutomatedTellerMachine.Services;

namespace AutomatedTellerMachine.Controllers
{
    [Authorize]
    public class TransactionController : Controller
    {
        private IApplicationDbContext db;

        public TransactionController()
        {
            db = new ApplicationDbContext();
        }

        public TransactionController(IApplicationDbContext dbContext)
        {
            db = dbContext;
        }

        // GET: Transaction/Deposit
        public ActionResult Deposit(int checkingAccountId)
        {
            return View();
        }

        // POST: Transaction/Deposit
        [HttpPost]
        public ActionResult Deposit(Transaction transaction)
        {
            if (ModelState.IsValid)
            {
                // Add transaction to db
                db.Transactions.Add(transaction);
                db.SaveChanges();

                // Update checking account balance
                var service = new CheckingAccountService(db);
                service.UpdateBalance(transaction.CheckingAccountId);

                return RedirectToAction("Index", "Home");
            }
            return View();
        }

        // GET: Transaction/Withdrawal
        public ActionResult Withdrawal(int checkingAccountId)
        {
            return View();
        }

        // POST: Transaction/Withdrawal
        [HttpPost]
        public ActionResult Withdrawal(Transaction transaction)
        {
            var checkingAccount = db.CheckingAccounts.Find(transaction.CheckingAccountId);
            if (transaction.Amount > checkingAccount.Balance)
            {
                ModelState.AddModelError("Amount", "You have insufficient funds!");
            }

            if (ModelState.IsValid)
            {
                // Add transaction to db
                transaction.Amount = -transaction.Amount;
                db.Transactions.Add(transaction);
                db.SaveChanges();

                // Update checking account balance
                var service = new CheckingAccountService(db);
                service.UpdateBalance(transaction.CheckingAccountId);

                return RedirectToAction("Index", "Home");
            }
            return View();
        }

        // GET: Transaction/QuickCash
        public ActionResult QuickCash(int checkingAccountId, decimal amount)
        {
            // Check for available funds
            var sourceCheckingAccount = db.CheckingAccounts.Find(checkingAccountId);
            var balance = sourceCheckingAccount.Balance;
            if (balance < amount)
            {
                return View("QuickCashInsufficientFunds");
            }

            // Add quick cash withdrawal transaction and update balance
            db.Transactions.Add(new Transaction { CheckingAccountId = checkingAccountId, Amount = -amount });
            db.SaveChanges();

            var service = new CheckingAccountService(db);
            service.UpdateBalance(checkingAccountId);

            // Return to home page after transaction completed
            return RedirectToAction("Index", "Home");
        }

        // GET: Transaction/Transfer
        public ActionResult Transfer(int checkingAccountId)
        {
            return View();
        }

        // POST: Transaction/Transfer
        [HttpPost]
        public ActionResult Transfer(TransferViewModel transfer)
        {
            // Check for available funds
            var sourceCheckingAccount = db.CheckingAccounts.Find(transfer.CheckingAccountId);
            if (transfer.Amount > sourceCheckingAccount.Balance)
            {
                ModelState.AddModelError("Amount", "You have insufficient funds!");
            }

            // Check for valid destination account
            var destinationCheckingAccount = db.CheckingAccounts.Where(c => c.AccountNumber == transfer.DestinationCheckingAccountId).FirstOrDefault();
            if (destinationCheckingAccount == null)
            {
                ModelState.AddModelError("DestinationCheckingAccountId", "Invalid destination account number.");
            }

            // Add debit/credit transactions and update account balances
            if (ModelState.IsValid)
            {
                db.Transactions.Add(new Transaction { CheckingAccountId = transfer.CheckingAccountId, Amount = -transfer.Amount });
                db.Transactions.Add(new Transaction { CheckingAccountId = destinationCheckingAccount.Id, Amount = transfer.Amount });
                db.SaveChanges();

                var service = new CheckingAccountService(db);
                service.UpdateBalance(transfer.CheckingAccountId);
                service.UpdateBalance(destinationCheckingAccount.Id);

                return PartialView("_TransferSuccess", transfer);
            }
            return PartialView("_TransferForm");
        }
    }
}

AutomatedTellerMachine/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

AutomatedTellerMachine/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

<div id="formSection">
    <h3>@ViewBag.TheMessage</h3>
    <form method="post" id="contactForm">
        <textarea name="message" id="message" maxlength="150" data-bind="value:message, valueUpdate:'input'"></textarea>
        <input type="submit" value="Send" />
        <span data-bind="text:charactersRemaining"></span> characters remaining
    </form>
    <img src="~/Content/Images/progress.gif" id="progress" style="display:none;" />
</div>

@section scripts 
{
    <script src="~/Scripts/knockout-3.4.2.js"></script>
    <script>
        function ContactViewModel() {
            var self = this;
            self.message = ko.observable('');
            self.charactersRemaining = ko.computed(function () {
                return 150 - self.message().length;
            })
        }
        ko.applyBindings(new ContactViewModel());
    </script>

    <script>
        $('#contactForm').submit(function () {
            $("#progress").show();
            $.post('', { message: $('#message').val() })
                .done(function (response) {
                    setTimeout(function () { $('#formSection').html(response); }, 2000);
                })
            return false;
        });
    </script>
}

@*Partial page updates using Microsoft jQuery Unobtrusive Ajax
<div id="formSection">
    <h3>@ViewBag.TheMessage</h3>
    @using (Ajax.BeginForm(new AjaxOptions {
            HttpMethod = "post",
            InsertionMode = InsertionMode.Replace,
            UpdateTargetId = "formSection"
            }))
    {
        <textarea name="message"></textarea>
        <input type="submit" value="Send" />
    }
</div>

@section scripts{
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
}*@

AutomatedTellerMachine/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
    //Layout = "MyLayout.cshtml";
}

<div class="row">
    <div class="col-md-6 margin-top-20">
        <a href="@Url.Action("Withdrawal", "Transaction", new { checkingAccountId = ViewBag.CheckingAccountId })" class="btn btn-primary btn-lg btn-block">
            <span class="glyphicon glyphicon-arrow-down"></span> Withdrawal
        </a>
        <a href="@Url.Action("QuickCash", "Transaction", new { checkingAccountId = ViewBag.CheckingAccountId, amount = 100 })" class="btn btn-primary btn-lg btn-block">
            <span class="glyphicon glyphicon-flash"></span> Quick Cash $100
        </a>
        <a href="@Url.Action("Details", "CheckingAccount")" class="btn btn-primary btn-lg btn-block">
            <span class="glyphicon glyphicon-question-sign"></span> Balance Inquiry
        </a>
    </div>
    <div class="col-md-6 margin-top-20">
        <a href="@Url.Action("Statement", "CheckingAccount", new { id = ViewBag.CheckingAccountId })" class="btn btn-primary btn-lg btn-block">
            <span class="glyphicon glyphicon-print"></span> Print Statement
        </a>
        <a href="@Url.Action("Transfer", "Transaction", new { checkingAccountId = ViewBag.CheckingAccountId })" class="btn btn-primary btn-lg btn-block">
            <span class="glyphicon glyphicon-transfer"></span> Transfer Funds
        </a>
        <a href="@Url.Action("Deposit", "Transaction", new { checkingAccountId = ViewBag.CheckingAccountId })" class="btn btn-primary btn-lg btn-block">
            <span class="glyphicon glyphicon-arrow-up"></span> Deposit
        </a>
    </div>
</div>

@ViewBag.Pin

@section scripts {
    <script>var testing = true;</script>
}

@*
    You are using @Request.Browser.Browser, and that's OK! Email us at support@mvcatm.com if you have any problems. Or send us a tweet @@mvcatm.

    @{ var amounts = new List<decimal> { 100, 25.50m, -40, 275.99m }; }
    <ul>
        @foreach (decimal amount in amounts)
        {
            <li>@formatAmount(amount)</li>
            <text>plain text</text>
            @:plain text
    }
    </ul>

        @helper formatAmount(decimal amount)
        {
            var color = "green";
            if (amount < 0)
        {
                color = "red";
        }
        <span style="color:@color">@String.Format("{0:c}", amount)</span>
    }
*@

AutomatedTellerMachine/Views/Home/_ContactThanks.cshtml
<h3>@ViewBag.TheMessage</h3>